// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx40i0EY9MVcp_QZX4VYZ9o5M49Wi8_NA',
    appId: '1:610453332136:web:2e5debc6f25d73015fe29d',
    messagingSenderId: '610453332136',
    projectId: 'fir-todo-fca84',
    authDomain: 'fir-todo-fca84.firebaseapp.com',
    storageBucket: 'fir-todo-fca84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiZCBOeRkYrdn-7n8k6qZ9X72ge7gwJ3o',
    appId: '1:610453332136:android:fda3cde2fb90b3e35fe29d',
    messagingSenderId: '610453332136',
    projectId: 'fir-todo-fca84',
    storageBucket: 'fir-todo-fca84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqVUug_sFWniOTv7i5HnNR1mgRZpzHnZ0',
    appId: '1:610453332136:ios:aa07c27a34aa0a515fe29d',
    messagingSenderId: '610453332136',
    projectId: 'fir-todo-fca84',
    storageBucket: 'fir-todo-fca84.appspot.com',
    iosClientId: '610453332136-cfohlh5mkt1jlnv3qmvc3va72go5pqkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqVUug_sFWniOTv7i5HnNR1mgRZpzHnZ0',
    appId: '1:610453332136:ios:aa07c27a34aa0a515fe29d',
    messagingSenderId: '610453332136',
    projectId: 'fir-todo-fca84',
    storageBucket: 'fir-todo-fca84.appspot.com',
    iosClientId: '610453332136-cfohlh5mkt1jlnv3qmvc3va72go5pqkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );
}
